# Generated by Django 5.0.2 on 2024-03-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_address1_shipingaddress_shipping_address1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipingaddress',
            options={'verbose_name_plural': 'Shipping Address'},
        ),
    ]
